name: Deploy to production

on:
  push:
    branches:
      - production

jobs:
  deploy_on_production:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to production
        run: |
          echo "Deploying to production..."

          echo "${{ secrets.SSH_PRIVATE_KEY_PRODUCTION }}" > ~/ssh_key
          chmod 600 ~/ssh_key

          ssh -o StrictHostKeyChecking=no \
            -i ~/ssh_key \
            ${{ secrets.PROD_HOST_USER }}@${{ secrets.PROD_HOST_IP }} << 'EOF'
          
          echo "Now inside the server"

          export NVM_DIR="$HOME/.nvm"
          [ -s "$NVM_DIR/nvm.sh" ] && . "$NVM_DIR/nvm.sh"

          cd /home/ubuntu/monorepo-continuous-deploy
          git checkout production
          git pull origin production
          pnpm install
          pnpm build

          pm2 restart all

          EOF
