name: Deploy to staging
on:
  push:
    branches:
      - staging

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy
        run: |
          echo "${{ secrets.SSH_PRIVATE_KEY_STAGING }}" > ~/ssh_key
          chmod 600 ~/ssh_key

          ssh -o StrictHostKeyChecking=no \
            -i ~/ssh_key \
            ${{ secrets.STAGING_USER }}@${{ secrets.STAGING_HOST_IP }} \
            "cd /home/ubuntu/monorepo-continuous-deploy && \
            git pull && \
            pnpm install && \
            pnpm build && \
            pm2 restart all"
          
        

